language: objective-c
osx_image: xcode9
script:
    - xcodebuild clean test -workspace Example/SlackWebAPIKit.xcworkspace -scheme SlackWebAPIKit-Example -destination "platform=iOS Simulator,name=iPhone 7,OS=10.3" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
